### PR TITLE
Ploidy

### PR DESCRIPTION
**Pull request by zeleniy**
Implement ploidy support.

### CODE REVIEW

**Comment by eweitz** [comment]
@zeleniy, @mrouard, thanks for this pull request to enable ploidy support (#47) as demonstrated at:

* [Ploidy, basic](https://zeleniy.github.io/ideogram/examples/polyploid.html)
* [Ploidy, chromosomal rearrangement](https://zeleniy.github.io/ideogram/examples/polyploid.html)

In the [chromosomal rearrangement](https://zeleniy.github.io/ideogram/examples/polyploid.html) example, there are ancestral chromosomes "A" and "B" in each chromosome set.  There seems to be an inconsistency in the way abnormal arms are depicted between "A" and "B" chromosomes.  Those on "A" are shown as an empty outline, whereas those on "B" are absent.  Is that expected?

**Comment by mrouard** [comment]
@eweitz, 
The way they are depicted is based on the ploidy paramter and not on the genome type. if your organism is expected to be triploid but you find an addtional arm, then the complementary arm is absent (since it is not expected). 
Conversely, if there is a loss of chromosome arm, then there is an empty outline to specify it.

This is the convention I have chosen. This is maybe not the best one. Please fell free to suggest any improvement.

**Comment by eweitz** [comment]
@mrouard, thanks for the clarification.  That seems like a reasonable convention.

@zeleniy, could you please fix the following issues in your branch?

1.  All examples broken in Internet Explorer.  Please ensure all examples in https://zeleniy.github.io/ideogram/examples/ work in IE 11 on Windows 7.  I do most of my development and testing in Chrome on Mac, but it is important that no examples fail to render in IE 11.  (Do not worry about testing in Edge.)  If you don't currently have access to Windows, perhaps check out [Browserstack](https://www.browserstack.com/test-in-internet-explorer) or [free VMs from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

2. Margin too wide between chromosomes.  Compare https://zeleniy.github.io/ideogram/examples/mouse.html and https://eweitz.github.io/ideogram/mouse.html.  The former should have the same amount of space as the latter between each chromosome.

3.  Too much space between labels and chromosomes.  Compare https://zeleniy.github.io/ideogram/examples/human.html and https://eweitz.github.io/ideogram/human.html.  The former should have the space amount of space as the latter between e.g. the label "1" and its corresponding chromosome.

4.  Chromosome labels not visible in rotated chromosomes.  Go to https://zeleniy.github.io/ideogram/examples/human.html, click on chromosome 1, and notice how the label disappears, unlike http://eweitz.github.io/ideogram/human.html.  

5.  Chromosome labels should not be bold in haploid chromosomes.  Font weight for labels in above  feature branch examples should match that in base branch.  Please either use standard font weight in all labels in all examples, or add special handling such that chromosome number label is bold in only ploidy examples.

6.  Chromosome labels misaligned with chromosome in examples with cytogenetic band labels.  In e.g. https://zeleniy.github.io/ideogram/examples/annotations_basic.html, please ensure the chromosome label "17" appears in precisely the same screen coordinates as it does in https://eweitz.github.io/ideogram/annotations_basic.html.

7.  Histogram not displayed.  Please ensure the histogram displays in https://zeleniy.github.io/ideogram/examples/annotations_histogram.html as it does in https://eweitz.github.io/ideogram/annotations_histogram.html.  The filters in the former should also work as they do in the latter.

**Comment by zeleniy** [comment]
Hi @eweitz, i have fixed almost all notices and have some comments to. Please check them out.

1. Fixed
2. Fixed
3. Fixed
4. Not fixed. That feature - rotation - always takes too much time when i am trying to work with it. I do not see sense of usage it, but of course you should decide to keep it or not. Anyway, for instance, if you click on 22 of [that example](https://eweitz.github.io/ideogram/human.html) you will see that scaling provided by `transform:scale` attribute distort original image and at all it looks not very pretty (unlike chromosome 1). I propose temporary to disable this feature and implement it later in other way. `Ideogram` class should provide public method `getChromosomeMode(length, width)` which should return model corresponding to passed `length` and `width` params. It will allow to manipulate chromosome in more clear way. What do you think?
5. Fixed
7. Fixed
8. Fixed

**Comment by eweitz** [comment]
@zeleniy, thanks for the fixes.  

Let's keep rotation enabled.  You're right that there is distortion in smaller chromosomes; it has always existed.  Nevertheless, animated rotation elicited audible "wows" when I demonstrated Ideogram.js in a bioinformatics hackathon, so I think it is worth showing.  I have opened #60 to track the pre-existing bug.

I see a few additional issues in your branch.  Once these are fixed, I will begin integration:

1.  Chromosome margin too wide.  There is more space between chromosomes than expected.  Compare https://zeleniy.github.io/ideogram/examples/human.html and https://eweitz.github.io/ideogram/human.html.

2.  Horizontally-oriented chromosomes shifted right.  Compare https://zeleniy.github.io/ideogram/examples/mouse.html and https://eweitz.github.io/ideogram/mouse.html.  See also "Brush" example.

3.  Horizontally-oriented chromosomes have downstream end truncated upon rotation.  Compare same examples as above issue.

4. In "Homology, interspecies" example, species label should be italicized and proceeded by a line break.  Compare https://eweitz.github.io/ideogram/homology_interspecies.html and https://zeleniy.github.io/ideogram/examples/homology_interspecies.html.

5.  In Git log, first two commits in feature branch have unlinked author.  Please [change the author information](https://help.github.com/articles/changing-author-info/) in those specific commits such that they link to the account you've used for the other commits.  It's OK that this rewrites part of the feature branch history.

Hopefully fixing the above issues will fix issue 4 from my previous comment, i.e. missing label upon rotation.  If not, I will try to fix it during my integration work.

**Comment by zeleniy** [comment]
Hi @eweitz, i have a progress:
1. Fixed
2. Yes, they are shifted. And this shift allow to show chromosome labels.
3. Fixed.
4. Fixed.
5. Hopefully fixed. At least i did as in documentation written. Anyway, the name of the committer is "Alexandr Zelenin" and this is too me.
5+. Now chromosome labels are visible on rotation.

**Pull request merged**
